#!/bin/sh
set -e
package_name=synaptic-eatmydata
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/sbin/synaptic"
    
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/locale/pt_BR/LC_MESSAGES/synaptic.mo"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/sbin/synaptic"

    dpkg-divert --package "$package_name" --rename --remove "/usr/share/locale/pt_BR/LC_MESSAGES/synaptic.mo"
;;
esac
exit 0
